### ISSUE TITLE
There should be a landing page for users opening repo.r-wasm.org in a browser

### ISSUE THREAD

**Issue by georgestagg** [r-wasm/webr-repo#12]
A simple `index.html` could be added to the output directory so that users opening the repo URL in a web browser see something better than an error page. A simple self-contained page would suffice, explaining what the repo is for.

Alternatively, the request could be forwarded to https://docs.r-wasm.org/webr/latest/packages.html

**Comment by HenrikBengtsson** [comment]
Along these lines: I think a lot of people go to <https://repo.r-wasm.org> to see which packages are currently available, so a redirect to <https://github.com/r-wasm/webr-repo/blob/main/repo-packages> would be the minimal change.

**Comment by HenrikBengtsson** [comment]
FWIW, <https://repo.r-wasm.org/> has been updated to give a direct link to this repo;


> # webR package repository
>
> This URL can be used with webR as a CRAN-like package repository. Please see <https://docs.r-wasm.org/webr/latest/packages.html> for further information.
> 
> A full list of available packages can be found at <https://github.com/r-wasm/webr-repo>.
