### ISSUE TITLE
Updating the 'Built' field in binary packages

### ISSUE THREAD

**Issue by jeroen** [r-wasm/webr-repo#30]
When cross-compiling packages with compiled code on Linux, the `DESCRIPTION` of the binary package contains:

```
Built: R 4.3.0; x86_64-pc-linux-gnu; 2023-09-01 13:04:10 UTC; unix
```

For the packages on `https://repo.r-wasm.org/` it says `aarch64-apple-darwin20` (I guess you cross-compile on m1). It would be nice to somehow fix the description to say wasm or emscripten instead of `x86_64-pc-linux-gnu`.

**Comment by georgestagg** [comment]
The new `rwasm` package I'm working on handles this via an R startup profile: https://github.com/r-wasm/rwasm/blob/main/inst/webr-profile
