### ISSUE TITLE
Bioconductor package support

### ISSUE THREAD

**Issue by j-andrews7** [r-wasm/webr-repo#33]
Are there any plans to support other high quality R package repos, e.g. Bioconductor? Doing so would immediately make a huge impact for many scientific fields.

**Comment by georgestagg** [comment]
We're not there yet, but I see no reason other repositories could not be used with webR in the future.

I'm going to close this issue for now, but once we're in a more stable position with CRAN packages and documentation for the Wasm package-building process, we'll start to think about other repositories.
