### ISSUE TITLE
Suggestion on packages to prioritize

### ISSUE THREAD

**Issue by bomeara** [r-wasm/webr-repo#9]
Thank you so much for your work on webr. It's truly amazing.

For usability, it seems like having many packages work will be key, but putting all 18K CRAN packages in webr-repo might be too much. The CRAN task views (https://cran.r-project.org/web/views/) might be a good way to prioritize packages: they're all things that are of some use to a subset of the R community. Within each view there are "core" packages in case filtering further is needed.

A different approach could be to run https://cran.r-project.org/web/packages/dlstats/ with a list of all CRAN packages to find the ones most commonly downloaded and just start working down the list.

**Comment by lionel-** [comment]
Thanks for the suggestion. We'll focus first on packages maintained by Posit and their dependencies, plus a few other high profile packages such as data.table and important modelling packages. Users will also be able to contribute ports if they need it.

For the moment there is no plan to support the entire CRAN library or even a large part of it. However we do plan to make all R-only packages (no native code) available within webR.
